import type { Metadata } from "next";

import Photo from "./Components/Photo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <div className="flex">
          <Photo />
          {children}
        </div>
      </body>
    </html>
  );
}
