import type { Metadata } from "next";
import "./globals.css";
import UserProvider from "./_Context/getCreateProfile";
import UserProviders from "./_Context/getUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <UserProviders>
          <UserProvider>{children}</UserProvider>
        </UserProviders>

      </body>
    </html>
  );
}
